#!/usr/bin/env bash
# low, normal, critical

# pkill dunst
# &> /dev/null dunst  \
#   -lf "$midground"  \
#   -nf "$color15"    \
#   -cf "$color15"    \
#   -lb "$color0"     \
#   -nb "$color0"     \
#   -cb "$color0"     \
#   -lfr "$highlight" \
#   -nfr "$highlight" \
#   -cfr "$highlight" \
#   -lh "$highlight"  \
#   -nh "$highlight"  \
#   -ch "$highlight"  \
#   & disown

pkill dunst
&>/dev/null dunst -config <(
  sed \
    -e "s/\( *frame_color *= *\).*$/\1\"$highlight\"/" \
    -e  "s/\( *highlight *= *\).*$/\1\"$highlight\"/" \
    -e "s/\( *background *= *\).*$/\1\"$background\"/" \
    -e "s/\( *foreground *= *\).*$/\1\"$foreground\"/" \
    -- $HOME/.config/dunst/dunstrc
  ) &