#!/usr/bin/env bash
# URxvt*background: [85]$color0

# opacity=88
# color0a="argb:${opacity}${color0#\#*}"

xrdb -merge <(cat <<EOF
URxvt*background: [100]$color0
URxvt*borderColor: [100]$color0
*fading: 20
*fadeColor: $color0
*cursorColor: $highlight
*cursorColor2: $color6
EOF
)

pkill -SIGUSR1 urxvt